### ISSUE TITLE
error when setting customized ticks in DataPlotter intiation

### ISSUE THREAD

**Issue by mileshsieh** [Aaron-Hsieh-0129/VVMTools#8]
data_dims = {'x':vvm.DIM['xc']/1.e3,\
                 'y':vvm.DIM['yc']/1.e3,\
                 'z':vvm.DIM['zc']/1.e3,\
                 't':np.arange(721)*np.timedelta64(2,'m')+np.datetime64('2024-01-01 05:00:00'),\
                }
    data_dim_units = {'x':'km',\
                      'y':'km',\
                      'z':'km',\
                      't':'LT',\
                     }
    tick_dims = {'x':np.arange(data_dims['x'][0], data_dims['x'][-1]+0.0001, 6.4),\
                 'y':np.arange(data_dims['y'][0], data_dims['y'][-1]+0.0001, 6.4),\
                 'z':np.arange(0, data_dims['z'].max()+0.00001,0.2),\
                 't':[np.datetime64(f'2024-01-01 00:00')+np.timedelta64(i,'h') for i in [5,6,12,18,24]],\
                }
    dplot = DataPlotter(exp, figpath, data_dims, data_dim_units, tick_dims)

<img width="1315" alt="圖片" src="https://github.com/user-attachments/assets/8c962aa9-c308-4ff7-bda1-dfc82bbc2bf7">

**Comment by Aaron-Hsieh-0129** [comment]
@tsengshao  I think it's the tick_dims problem which we didn't provide this option in the hw7.2 so don't worry about this. Could you deal with the bug?

**Comment by tsengshao** [comment]
Sure
